j2s7s300:
  effort_finger_trajectory_controller:
    constraints:
      goal_time: 1.0
      j2s7s300_joint_finger_1:
        goal: 0.02
        trajectory: 0.05
      j2s7s300_joint_finger_2:
        goal: 0.02
        trajectory: 0.05
      j2s7s300_joint_finger_3:
        goal: 0.02
        trajectory: 0.05
      stopped_velocity_tolerance: 0.02
    gains:
      j2s7s300_joint_finger_1:
        d: 0
        i: 0
        i_clamp: 1
        p: 10
      j2s7s300_joint_finger_2:
        d: 0
        i: 0
        i_clamp: 1
        p: 10
      j2s7s300_joint_finger_3:
        d: 0
        i: 0
        i_clamp: 1
        p: 10
    joints:
    - j2s7s300_joint_finger_1
    - j2s7s300_joint_finger_2
    - j2s7s300_joint_finger_3
    type: effort_controllers/JointTrajectoryController
  finger_1_position_controller:
    joint: j2s7s300_joint_finger_1
    pid:
      d: 0
      i: 0
      p: 10
    type: effort_controllers/JointPositionController
  finger_2_position_controller:
    joint: j2s7s300_joint_finger_2
    pid:
      d: 0
      i: 0
      p: 10
    type: effort_controllers/JointPositionController
  finger_3_position_controller:
    joint: j2s7s300_joint_finger_3
    pid:
      d: 0
      i: 0
      p: 10
    type: effort_controllers/JointPositionController
  finger_tip_1_position_controller:
    joint: j2s7s300_joint_finger_tip_1
    pid:
      d: 0
      i: 0
      p: 0.5
    type: effort_controllers/JointPositionController
  finger_tip_2_position_controller:
    joint: j2s7s300_joint_finger_tip_2
    pid:
      d: 0
      i: 0
      p: 0.5
    type: effort_controllers/JointPositionController
  finger_tip_3_position_controller:
    joint: j2s7s300_joint_finger_tip_3
    pid:
      d: 0
      i: 0
      p: 0.5
    type: effort_controllers/JointPositionController
  joint_state_controller:
    publish_rate: 50
    type: joint_state_controller/JointStateController
  position_joint_trajectory_controller:
    joints:
    - j2s7s300_joint_1
    - j2s7s300_joint_2
    - j2s7s300_joint_3
    - j2s7s300_joint_4
    - j2s7s300_joint_5
    - j2s7s300_joint_6
    - j2s7s300_joint_7
    type: position_controllers/JointTrajectoryController



      


